/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.sergiogomez.vista;

import biblioteca.sergiogomez.Modelo.Carnet;
import biblioteca.sergiogomez.Modelo.ModeloTablaUsuarios;
import biblioteca.sergiogomez.Modelo.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Sergio
 * La clase se encuentra terminada, solo falta comprobar los textfile como por ejemplo telefono que solo pueda introducir numeros y el email solo email y listo
 */
public class GestionUsuarios extends javax.swing.JInternalFrame implements ActionListener,MouseListener {
    private int filaSeleccionada=-1;
    private final AbstractTableModel modeloTabla;
    private boolean actualizado=false;
    /**
     * Creates new form GestionUsuarios
     */
    public GestionUsuarios() {
        modeloTabla=new ModeloTablaUsuarios();
        initComponents();
        iniciarListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        contrasena = new javax.swing.JTextField();
        carnet = new javax.swing.JButton();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/sergiogomez/imagenes/login.png"))); // NOI18N

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Direccion");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Telefono");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Email");

        add.setText("Añadir");

        borrar.setText("Borrar");

        modificar.setText("Modificar");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nombre Usuario");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Contraseña");

        carnet.setActionCommand("Carnet");
        carnet.setLabel("Carnet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(carnet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(contrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(borrar)
                    .addComponent(modificar)
                    .addComponent(carnet))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton borrar;
    private javax.swing.JButton carnet;
    private javax.swing.JTextField contrasena;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case "Borrar":
                borrarUsuario();
                break;
            case "Modificar":
                preActualizar();
                break;
            case "Añadir":
                anadirUsuario();
                break;
            case "Carnet":
                crearCarnet();
                break;
        }
    }
    
    public void crearCarnet()
    {
        try {
            if(filaSeleccionada!=0){
                Carnet carnet=new Carnet(Principal.getBiblioteca().getUsuarios().get(filaSeleccionada).getId());
            }else{
                JOptionPane.showMessageDialog(null,"El usuario Admin no tiene carnet.","Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Ha ocurrido un error en la creacion del Carnet.","Error", JOptionPane.ERROR_MESSAGE);
        }catch(IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(null,"No has seleccionado ninguna fila campo.","Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    @Override
    public void mouseClicked(MouseEvent e) {
        filaSeleccionada=jTable1.getSelectedRow(); 
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    private void preActualizar(){
        int index=filaSeleccionada;
        try{
            if(actualizado==false){
                nombreUsuario.setText(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
                contrasena.setText(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
                nombre.setText(modeloTabla.getValueAt(filaSeleccionada, 2).toString());
                apellidos.setText(modeloTabla.getValueAt(filaSeleccionada, 3).toString());
                direccion.setText(modeloTabla.getValueAt(filaSeleccionada, 4).toString());
                telefono.setText(modeloTabla.getValueAt(filaSeleccionada, 5).toString());
                email.setText(modeloTabla.getValueAt(filaSeleccionada, 6).toString());
                add.setEnabled(false);
                borrar.setEnabled(false);
                actualizado=true;
            }else{
                add.setEnabled(true);
                borrar.setEnabled(true);
                actualizar(index);
                actualizado=false;
                vaciarCampos();
            }
        }catch(IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(null,"No has seleccionado ninguna fila campo.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizar(int index){
        if(!contrasena.getText().isEmpty() && !nombreUsuario.getText().isEmpty() && !nombre.getText().isEmpty() && !apellidos.getText().isEmpty() && !direccion.getText().isEmpty() && !telefono.getText().isEmpty() && !email.getText().isEmpty()){
            if( Principal.getBiblioteca().getUsuarios().get(index).getNombreUsuario().equalsIgnoreCase(nombreUsuario.getText()) || !Principal.getConexion().existeUsuario(nombreUsuario.getText())){
                Principal.getBiblioteca().getUsuarios().get(index).setNombreUsuario(nombreUsuario.getText());
                Principal.getBiblioteca().getUsuarios().get(index).setNombre(nombre.getText());
                Principal.getBiblioteca().getUsuarios().get(index).setApellido(apellidos.getText());
                Principal.getBiblioteca().getUsuarios().get(index).setDireccion(direccion.getText());
                Principal.getBiblioteca().getUsuarios().get(index).setTelefono(telefono.getText());
                Principal.getBiblioteca().getUsuarios().get(index).setEmail(email.getText());
                Principal.getBiblioteca().getUsuarios().get(index).setContrasena(contrasena.getText());
                Principal.getConexion().actualizarUsuario(Principal.getBiblioteca().getUsuarios().get(index));                
                modeloTabla.fireTableDataChanged();
                vaciarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"El nombre de usuario ya existe en el sistema.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debes introducir todos los campos.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void anadirUsuario() {
        if(!contrasena.getText().isEmpty() && !nombreUsuario.getText().isEmpty() && !nombre.getText().isEmpty() && !apellidos.getText().isEmpty() && !direccion.getText().isEmpty() && !telefono.getText().isEmpty() && !email.getText().isEmpty()){
            if(!Principal.getConexion().existeUsuario(nombreUsuario.getText())){
                Usuario usuario=new Usuario(Principal.getConexion().nuevoIdUsuario(),nombreUsuario.getText(),nombre.getText(),apellidos.getText(),direccion.getText(),telefono.getText(),email.getText(),contrasena.getText());
                Principal.getBiblioteca().getUsuarios().add(usuario);
                Principal.getConexion().addUsuario(usuario,contrasena.getText());
                modeloTabla.fireTableDataChanged();
                vaciarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"El nombre de usuario ya existe en el sistema.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debes rellenar todos los campos.","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    private void borrarUsuario(){
        try{
            if(filaSeleccionada!=-1){
                if(Principal.getBiblioteca().getUsuarios().get(filaSeleccionada).getId()==1){
                    JOptionPane.showMessageDialog(null,"El usuario administrador no puede ser borrado.","Error", JOptionPane.ERROR_MESSAGE);
                }else{
                    Principal.getConexion().borrarUsuario(Principal.getBiblioteca().getUsuarios().get(filaSeleccionada).getId());
                    Principal.getBiblioteca().getUsuarios().remove(filaSeleccionada);
                    modeloTabla.fireTableDataChanged();
                }
            }else{
                JOptionPane.showMessageDialog(null,"Selecciona una fila.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(null,"Selecciona una fila.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void vaciarCampos(){
        nombreUsuario.setText("");
        nombre.setText("");
        apellidos.setText("");
        direccion.setText("");
        telefono.setText("");
        email.setText("");
        contrasena.setText("");
    }

    private void iniciarListeners() {
        jTable1.addMouseListener(this);
        add.addActionListener(this);
        borrar.addActionListener(this);
        modificar.addActionListener(this);
        carnet.addActionListener(this);
    }
}
