/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.sergiogomez.vista;

import biblioteca.sergiogomez.DAO.Modelo.Libro;
import biblioteca.sergiogomez.DAO.Modelo.ModeloTablaLibros;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Sergio
 * La clase se encuentra terminada, solo falta comprobar los textfile como por ejemplo telefono que solo pueda introducir numeros y el email solo email y listo
 */
public class GestionLibros extends javax.swing.JInternalFrame implements ActionListener,MouseListener {
    private int filaSeleccionada=-1;
    private final AbstractTableModel modeloTabla;
    private boolean actualizado=false;
    /**
     * Creates new form GestionUsuarios
     */
    public GestionLibros() {
        modeloTabla=new ModeloTablaLibros();
        initComponents();
        iniciarListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/sergiogomez/imagenes/login.png"))); // NOI18N

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        add.setText("Añadir");

        borrar.setText("Borrar");

        modificar.setText("Modificar");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Titulo");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("ISBN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificar))
                            .addComponent(isbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(95, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 107, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add)
                        .addComponent(borrar)
                        .addComponent(modificar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Titulo;
    private javax.swing.JButton add;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case "Borrar":
                borrarLibro();
                break;
            case "Modificar":
                preActualizar();
                break;
            case "Añadir":
                anadirLibro();
                break;        
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
        filaSeleccionada=jTable1.getSelectedRow(); 
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    private void preActualizar(){
        int index=filaSeleccionada;
        try{
            if(actualizado==false){
                Titulo.setText(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
                isbn.setText(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
                add.setEnabled(false);
                borrar.setEnabled(false);
                actualizado=true;
            }else{
                add.setEnabled(true);
                borrar.setEnabled(true);
                actualizar(index);
                actualizado=false;
                vaciarCampos();
            }
        }catch(IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(null,"No has seleccionado ninguna fila campo.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizar(int index){
        if(!isbn.getText().isEmpty() && !Titulo.getText().isEmpty()){
            if( Principal.getBiblioteca().getLibros().get(index).getTitulo().equalsIgnoreCase(Titulo.getText()) || !Principal.getConexion().existeUsuario(Titulo.getText())){
                Principal.getBiblioteca().getLibros().get(index).setTitulo(Titulo.getText());
                Principal.getBiblioteca().getLibros().get(index).setISBN(isbn.getText());
                Principal.getConexion().actualizarLibros(Principal.getBiblioteca().getLibros().get(index));                
                modeloTabla.fireTableDataChanged();
                vaciarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"El nombre de usuario ya existe en el sistema.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debes introducir todos los campos.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void anadirLibro() {
        if(!isbn.getText().isEmpty() && !Titulo.getText().isEmpty()){
            if(!Principal.getConexion().existeLibro(isbn.getText())){
                Libro libro=new Libro(Titulo.getText(),isbn.getText(),0);
                Principal.getBiblioteca().getLibros().add(libro);
                Principal.getConexion().addLibro(libro);
                modeloTabla.fireTableDataChanged();
                vaciarCampos();
            }else{
                JOptionPane.showMessageDialog(null,"El ISBN de libro ya existe en el sistema.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Debes rellenar todos los campos.","Error", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    private void borrarLibro(){
        try{
            if(filaSeleccionada!=-1){
                Principal.getConexion().borrarLibro(Principal.getBiblioteca().getLibros().get(filaSeleccionada).getISBN());
                Principal.getBiblioteca().getLibros().remove(filaSeleccionada);
                modeloTabla.fireTableDataChanged();
            }else{
                JOptionPane.showMessageDialog(null,"Selecciona una fila.","Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(IndexOutOfBoundsException iobe){
            JOptionPane.showMessageDialog(null,"Selecciona una fila.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void vaciarCampos(){
        Titulo.setText("");
        isbn.setText("");
    }

    private void iniciarListeners() {
        jTable1.addMouseListener(this);
        add.addActionListener(this);
        borrar.addActionListener(this);
        modificar.addActionListener(this);
    }
}
