/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca.sergiogomez.vista;

import biblioteca.sergiogomez.DAO.ClaseDAO;
import biblioteca.sergiogomez.Modelo.Biblioteca;
import biblioteca.sergiogomez.Modelo.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JDesktopPane;

/**
 *
 * @author Sergio
 */
public class Principal extends javax.swing.JFrame implements ActionListener {
    public static JDesktopPane desktop;
    private static ClaseDAO conexion;
    private static Usuario sesion;
    private static Biblioteca biblioteca;

    public static Biblioteca getBiblioteca() {
        return biblioteca;
    }

    public static void setBiblioteca(Biblioteca biblioteca) {
        Principal.biblioteca = biblioteca;
    }

    public static Usuario getSesion() {
        return sesion;
    }

    public static void setSesion(Usuario sesion) {
        Principal.sesion = sesion;
    }
    
    public static JDesktopPane getDesktop() {
        return desktop;
    }

    public static void setDesktop(JDesktopPane desktop) {
        Principal.desktop = desktop;
    } 

    public static ClaseDAO getConexion() {
        return conexion;
    }

    public static void setConexion(ClaseDAO conexion) {
        Principal.conexion = conexion;
    }

    private void TipoSesion() {
        try{
            if(!getSesion().getNombreUsuario().equals("Admin")){
                jMenu2.setVisible(false);
                jMenu3.setVisible(true);
                menuExit.setVisible(true);
                menuLogin.setEnabled(true);
                menuCambiarContrasena.setVisible(true);
            }else{
                jMenu2.setVisible(true);
                menuExit.setVisible(true);
                menuLogin.setEnabled(true);
                menuCambiarContrasena.setVisible(true); 
            }
        }catch(NullPointerException npe){
            System.exit(0);
        }
    }
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        setConexion(new ClaseDAO());
        biblioteca=new Biblioteca();
        biblioteca.setUsuarios(conexion.cargarUsuarios());
        biblioteca.setLibros(conexion.cargarLibros());
        initComponents();
        dimensionarPantalla();
        iniciarDesktop();
        anadirListeners();
        ocultarElementos();
        mostrarLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuCambiarContrasena = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        adminUsuarios = new javax.swing.JMenuItem();
        adminLibros = new javax.swing.JMenuItem();
        prestamos = new javax.swing.JMenuItem();
        verPrestamos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        verMisPrestamos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Inicio");

        menuLogin.setText("Login");
        menuLogin.setToolTipText("");
        jMenu1.add(menuLogin);

        menuCambiarContrasena.setText("Cambiar Contraseña");
        jMenu1.add(menuCambiarContrasena);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu Administrador");

        adminUsuarios.setText("Admin Usuarios");
        jMenu2.add(adminUsuarios);

        adminLibros.setText("Admin Libros");
        jMenu2.add(adminLibros);

        prestamos.setText("Prestamos");
        jMenu2.add(prestamos);

        verPrestamos.setText("Ver prestamos");
        jMenu2.add(verPrestamos);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mis prestamos");

        verMisPrestamos.setText("Ver mis prestamos");
        jMenu3.add(verMisPrestamos);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adminLibros;
    private javax.swing.JMenuItem adminUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCambiarContrasena;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem prestamos;
    private javax.swing.JMenuItem verMisPrestamos;
    private javax.swing.JMenuItem verPrestamos;
    // End of variables declaration//GEN-END:variables

    private void iniciarDesktop() {
        desktop=new JDesktopPane();
        setContentPane(desktop);
        desktop.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE); 
    }
    
    private void mostrarLogin(){
        menuLogin.setEnabled(false);
        DialogoLogin frame=new DialogoLogin(this, true);
        frame.setVisible(true);
        TipoSesion();        
    }

    private void dimensionarPantalla() {
        Dimension dimension=Toolkit.getDefaultToolkit().getScreenSize();
        int alto=(int)dimension.getHeight()-50;
        int ancho=(int) dimension.getWidth();
        setSize(ancho, alto);
    }

    private void anadirListeners() {
        menuExit.addActionListener(this);
        menuLogin.addActionListener(this);
        menuCambiarContrasena.addActionListener(this);
        adminUsuarios.addActionListener(this);
        adminLibros.addActionListener(this);
        prestamos.addActionListener(this);
        verPrestamos.addActionListener(this);
        verMisPrestamos.addActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        switch(e.getActionCommand()){
            case "Exit":
                System.exit(0);               
                break;
            case "Login":
                mostrarLogin();
                break;
            case "Cambiar Contraseña":
                mostrarcambiarContrasena();
                break;
            case "Admin Usuarios":
                mostrarAdminUsuarios();
                break;
            case "Admin Libros":
                mostrarAdminLibros();
                break;
            case "Prestamos":
                mostrarSeleccionDeUsuario();
                break;
            case "Ver prestamos":
                mostrarSeleccionDeUsuarioPrestamos();
                break;
            case "Ver mis prestamos":
                verPrestamosUSuario();
                break;
        }
    }

    
    private void verPrestamosUSuario(){
        ListarPrestamosDeUsuario frame=new ListarPrestamosDeUsuario(getSesion());
        frame.setLocation((Principal.desktop.getWidth()-frame.getWidth())/2,(Principal.desktop.getHeight()-frame.getHeight())/2);
        frame.setVisible(true);
        Principal.desktop.add(frame);
    }
    
    private void mostrarcambiarContrasena() {
        CambiarContrasena frame=new CambiarContrasena();
        frame.setLocation((desktop.getWidth()-frame.getWidth())/2,(desktop.getHeight()-frame.getHeight())/2);
        frame.setVisible(true);
        desktop.add(frame);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
    }

    private void mostrarAdminUsuarios() {
        GestionUsuarios frame=new GestionUsuarios();
        frame.setLocation((desktop.getWidth()-frame.getWidth())/2,(desktop.getHeight()-frame.getHeight())/2);
        frame.setVisible(true);
        desktop.add(frame);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
    }
    
    private void mostrarSeleccionDeUsuario() {
        SeleccionDeUsuarioParaPrestamo frame=new SeleccionDeUsuarioParaPrestamo();
        frame.setLocation((desktop.getWidth()-frame.getWidth())/2,(desktop.getHeight()-frame.getHeight())/2);
        frame.setVisible(true);
        desktop.add(frame);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
    }
    
    private void mostrarAdminLibros(){
        GestionLibros frame=new GestionLibros();
        frame.setLocation((desktop.getWidth()-frame.getWidth())/2,(desktop.getHeight()-frame.getHeight())/2);
        frame.setVisible(true);
        desktop.add(frame);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}   
    
    }

    private void ocultarElementos() {
        jMenu2.setVisible(false);
        jMenu3.setVisible(false);
        menuExit.setVisible(true);
        menuLogin.setEnabled(false);
        menuCambiarContrasena.setVisible(false);
    }

    private void mostrarSeleccionDeUsuarioPrestamos() {
        SeleccionDeUsuarioParaListarPrestamos frame=new SeleccionDeUsuarioParaListarPrestamos();
        frame.setLocation((desktop.getWidth()-frame.getWidth())/2,(desktop.getHeight()-frame.getHeight())/2);
        frame.setVisible(true);
        desktop.add(frame);
        try {
            frame.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {}
    }
    
}
